/*
 * THE FILE IS GENERATED by TGen.
 * Tue May 05 23:03:08 2020
 */

#include "unity_fixture.h"
#include "CCodeParse.h"

TEST_GROUP(CCodeParse_Test);

TEST_SETUP(CCodeParse_Test)
{

}

TEST_TEAR_DOWN(CCodeParse_Test)
{

}

TEST(CCodeParse_Test, CCP_GetCwd)
{

}

TEST(CCodeParse_Test, CCP_SetCwd)
{

}

TEST(CCodeParse_Test, CCP_IsFilePathVaild)
{

}

TEST(CCodeParse_Test, CCP_PrintfMessage)
{

}

TEST(CCodeParse_Test, CCP_StringSubtract)
{

}

TEST(CCodeParse_Test, CCP_CombinePath)
{

}

TEST(CCodeParse_Test, CCP_GetDirFileInfo)
{

}

TEST(CCodeParse_Test, CCP_GetFuncNameFormSource)
{

}

TEST(CCodeParse_Test, CCP_Free)
{

}

