/*
 * THE FILE IS GENERATED by TGen.
 * Thu May 07 07:25:50 2020
 */

#include "unity_fixture.h"
#include "GeneratorOutputPrivate.h"

TEST_GROUP(GeneratorOutputPrivate_Test);

TEST_SETUP(GeneratorOutputPrivate_Test)
{

}

TEST_TEAR_DOWN(GeneratorOutputPrivate_Test)
{

}

TEST(GeneratorOutputPrivate_Test, outputCFileCreate)
{

}

TEST(GeneratorOutputPrivate_Test, outputCFileDestory)
{

}

TEST(GeneratorOutputPrivate_Test, outputCFileGenerateMessage)
{

}

TEST(GeneratorOutputPrivate_Test, outputCFileHead)
{

}

TEST(GeneratorOutputPrivate_Test, outputCFileFunctionStart)
{

}

TEST(GeneratorOutputPrivate_Test, outputCFileFunctionCall)
{

}

TEST(GeneratorOutputPrivate_Test, outputCFileFunctionEnd)
{

}

TEST(GeneratorOutputPrivate_Test, outputCFileBlankLine)
{

}

