/*
 * THE FILE IS GENERATED by TGen.
 * Tue May 05 23:03:08 2020
 */

#include "unity_fixture.h"
#include "mpc.h"

TEST_GROUP(mpc_Test);

TEST_SETUP(mpc_Test)
{

}

TEST_TEAR_DOWN(mpc_Test)
{

}

TEST(mpc_Test, mpc_err_delete)
{

}

TEST(mpc_Test, mpc_err_string)
{

}

TEST(mpc_Test, mpc_err_print)
{

}

TEST(mpc_Test, mpc_err_print_to)
{

}

TEST(mpc_Test, mpc_parse)
{

}

TEST(mpc_Test, mpc_nparse)
{

}

TEST(mpc_Test, mpc_parse_file)
{

}

TEST(mpc_Test, mpc_parse_pipe)
{

}

TEST(mpc_Test, mpc_parse_contents)
{

}

TEST(mpc_Test, mpc_new)
{

}

TEST(mpc_Test, mpc_copy)
{

}

TEST(mpc_Test, mpc_define)
{

}

TEST(mpc_Test, mpc_undefine)
{

}

TEST(mpc_Test, mpc_delete)
{

}

TEST(mpc_Test, mpc_cleanup)
{

}

TEST(mpc_Test, mpc_any)
{

}

TEST(mpc_Test, mpc_char)
{

}

TEST(mpc_Test, mpc_range)
{

}

TEST(mpc_Test, mpc_oneof)
{

}

TEST(mpc_Test, mpc_noneof)
{

}

TEST(mpc_Test, mpc_satisfy)
{

}

TEST(mpc_Test, mpc_string)
{

}

TEST(mpc_Test, mpc_pass)
{

}

TEST(mpc_Test, mpc_fail)
{

}

TEST(mpc_Test, mpc_failf)
{

}

TEST(mpc_Test, mpc_lift)
{

}

TEST(mpc_Test, mpc_lift_val)
{

}

TEST(mpc_Test, mpc_anchor)
{

}

TEST(mpc_Test, mpc_state)
{

}

TEST(mpc_Test, mpc_expect)
{

}

TEST(mpc_Test, mpc_expectf)
{

}

TEST(mpc_Test, mpc_apply)
{

}

TEST(mpc_Test, mpc_apply_to)
{

}

TEST(mpc_Test, mpc_check)
{

}

TEST(mpc_Test, mpc_check_with)
{

}

TEST(mpc_Test, mpc_checkf)
{

}

TEST(mpc_Test, mpc_check_withf)
{

}

TEST(mpc_Test, mpc_not)
{

}

TEST(mpc_Test, mpc_not_lift)
{

}

TEST(mpc_Test, mpc_maybe)
{

}

TEST(mpc_Test, mpc_maybe_lift)
{

}

TEST(mpc_Test, mpc_many)
{

}

TEST(mpc_Test, mpc_many1)
{

}

TEST(mpc_Test, mpc_count)
{

}

TEST(mpc_Test, mpc_or)
{

}

TEST(mpc_Test, mpc_and)
{

}

TEST(mpc_Test, mpc_predictive)
{

}

TEST(mpc_Test, mpc_eoi)
{

}

TEST(mpc_Test, mpc_soi)
{

}

TEST(mpc_Test, mpc_boundary)
{

}

TEST(mpc_Test, mpc_boundary_newline)
{

}

TEST(mpc_Test, mpc_whitespace)
{

}

TEST(mpc_Test, mpc_whitespaces)
{

}

TEST(mpc_Test, mpc_blank)
{

}

TEST(mpc_Test, mpc_newline)
{

}

TEST(mpc_Test, mpc_tab)
{

}

TEST(mpc_Test, mpc_escape)
{

}

TEST(mpc_Test, mpc_digit)
{

}

TEST(mpc_Test, mpc_hexdigit)
{

}

TEST(mpc_Test, mpc_octdigit)
{

}

TEST(mpc_Test, mpc_digits)
{

}

TEST(mpc_Test, mpc_hexdigits)
{

}

TEST(mpc_Test, mpc_octdigits)
{

}

TEST(mpc_Test, mpc_lower)
{

}

TEST(mpc_Test, mpc_upper)
{

}

TEST(mpc_Test, mpc_alpha)
{

}

TEST(mpc_Test, mpc_underscore)
{

}

TEST(mpc_Test, mpc_alphanum)
{

}

TEST(mpc_Test, mpc_int)
{

}

TEST(mpc_Test, mpc_hex)
{

}

TEST(mpc_Test, mpc_oct)
{

}

TEST(mpc_Test, mpc_number)
{

}

TEST(mpc_Test, mpc_real)
{

}

TEST(mpc_Test, mpc_float)
{

}

TEST(mpc_Test, mpc_char_lit)
{

}

TEST(mpc_Test, mpc_string_lit)
{

}

TEST(mpc_Test, mpc_regex_lit)
{

}

TEST(mpc_Test, mpc_ident)
{

}

TEST(mpc_Test, mpc_startwith)
{

}

TEST(mpc_Test, mpc_endwith)
{

}

TEST(mpc_Test, mpc_whole)
{

}

TEST(mpc_Test, mpc_stripl)
{

}

TEST(mpc_Test, mpc_stripr)
{

}

TEST(mpc_Test, mpc_strip)
{

}

TEST(mpc_Test, mpc_tok)
{

}

TEST(mpc_Test, mpc_sym)
{

}

TEST(mpc_Test, mpc_total)
{

}

TEST(mpc_Test, mpc_between)
{

}

TEST(mpc_Test, mpc_parens)
{

}

TEST(mpc_Test, mpc_braces)
{

}

TEST(mpc_Test, mpc_brackets)
{

}

TEST(mpc_Test, mpc_squares)
{

}

TEST(mpc_Test, mpc_tok_between)
{

}

TEST(mpc_Test, mpc_tok_parens)
{

}

TEST(mpc_Test, mpc_tok_braces)
{

}

TEST(mpc_Test, mpc_tok_brackets)
{

}

TEST(mpc_Test, mpc_tok_squares)
{

}

TEST(mpc_Test, mpcf_dtor_null)
{

}

TEST(mpc_Test, mpcf_ctor_null)
{

}

TEST(mpc_Test, mpcf_ctor_str)
{

}

TEST(mpc_Test, mpcf_free)
{

}

TEST(mpc_Test, mpcf_int)
{

}

TEST(mpc_Test, mpcf_hex)
{

}

TEST(mpc_Test, mpcf_oct)
{

}

TEST(mpc_Test, mpcf_float)
{

}

TEST(mpc_Test, mpcf_strtriml)
{

}

TEST(mpc_Test, mpcf_strtrimr)
{

}

TEST(mpc_Test, mpcf_strtrim)
{

}

TEST(mpc_Test, mpcf_escape)
{

}

TEST(mpc_Test, mpcf_escape_regex)
{

}

TEST(mpc_Test, mpcf_escape_string_raw)
{

}

TEST(mpc_Test, mpcf_escape_char_raw)
{

}

TEST(mpc_Test, mpcf_unescape)
{

}

TEST(mpc_Test, mpcf_unescape_regex)
{

}

TEST(mpc_Test, mpcf_unescape_string_raw)
{

}

TEST(mpc_Test, mpcf_unescape_char_raw)
{

}

TEST(mpc_Test, mpcf_null)
{

}

TEST(mpc_Test, mpcf_fst)
{

}

TEST(mpc_Test, mpcf_snd)
{

}

TEST(mpc_Test, mpcf_trd)
{

}

TEST(mpc_Test, mpcf_fst_free)
{

}

TEST(mpc_Test, mpcf_snd_free)
{

}

TEST(mpc_Test, mpcf_trd_free)
{

}

TEST(mpc_Test, mpcf_all_free)
{

}

TEST(mpc_Test, mpcf_strfold)
{

}

TEST(mpc_Test, mpcf_maths)
{

}

TEST(mpc_Test, mpc_re)
{

}

TEST(mpc_Test, mpc_re_mode)
{

}

TEST(mpc_Test, mpc_ast_new)
{

}

TEST(mpc_Test, mpc_ast_build)
{

}

TEST(mpc_Test, mpc_ast_add_root)
{

}

TEST(mpc_Test, mpc_ast_add_child)
{

}

TEST(mpc_Test, mpc_ast_add_tag)
{

}

TEST(mpc_Test, mpc_ast_add_root_tag)
{

}

TEST(mpc_Test, mpc_ast_tag)
{

}

TEST(mpc_Test, mpc_ast_state)
{

}

TEST(mpc_Test, mpc_ast_delete)
{

}

TEST(mpc_Test, mpc_ast_print)
{

}

TEST(mpc_Test, mpc_ast_print_to)
{

}

TEST(mpc_Test, mpc_ast_get_index)
{

}

TEST(mpc_Test, mpc_ast_get_index_lb)
{

}

TEST(mpc_Test, mpc_ast_get_child)
{

}

TEST(mpc_Test, mpc_ast_get_child_lb)
{

}

TEST(mpc_Test, mpc_ast_traverse_start)
{

}

TEST(mpc_Test, mpc_ast_traverse_next)
{

}

TEST(mpc_Test, mpc_ast_traverse_free)
{

}

TEST(mpc_Test, mpc_ast_eq)
{

}

TEST(mpc_Test, mpcf_fold_ast)
{

}

TEST(mpc_Test, mpcf_str_ast)
{

}

TEST(mpc_Test, mpcf_state_ast)
{

}

TEST(mpc_Test, mpca_tag)
{

}

TEST(mpc_Test, mpca_add_tag)
{

}

TEST(mpc_Test, mpca_root)
{

}

TEST(mpc_Test, mpca_state)
{

}

TEST(mpc_Test, mpca_total)
{

}

TEST(mpc_Test, mpca_not)
{

}

TEST(mpc_Test, mpca_maybe)
{

}

TEST(mpc_Test, mpca_many)
{

}

TEST(mpc_Test, mpca_many1)
{

}

TEST(mpc_Test, mpca_count)
{

}

TEST(mpc_Test, mpca_or)
{

}

TEST(mpc_Test, mpca_and)
{

}

TEST(mpc_Test, mpca_grammar)
{

}

TEST(mpc_Test, mpca_lang)
{

}

TEST(mpc_Test, mpca_lang_file)
{

}

TEST(mpc_Test, mpca_lang_pipe)
{

}

TEST(mpc_Test, mpca_lang_contents)
{

}

TEST(mpc_Test, mpc_print)
{

}

TEST(mpc_Test, mpc_optimise)
{

}

TEST(mpc_Test, mpc_stats)
{

}

TEST(mpc_Test, mpc_test_pass)
{

}

TEST(mpc_Test, mpc_test_fail)
{

}

