/*
 * THE FILE IS GENERATED by TGen.
 * Thu May 07 07:25:50 2020
 */

#include "unity_fixture.h"
#include "stringHelper.h"

TEST_GROUP(stringHelper_Test);

TEST_SETUP(stringHelper_Test)
{

}

TEST_TEAR_DOWN(stringHelper_Test)
{

}

TEST(stringHelper_Test, SL_StringTrim)
{

}

TEST(stringHelper_Test, SL_StringTrimString)
{

}

TEST(stringHelper_Test, SL_StringTrimLeadWhitespace)
{

}

TEST(stringHelper_Test, SL_StringReplace)
{

}

TEST(stringHelper_Test, SL_StringAppend)
{

}

TEST(stringHelper_Test, SL_StringAddHead)
{

}

TEST(stringHelper_Test, SL_StringSubstring)
{

}

TEST(stringHelper_Test, SL_StringWithEnds)
{

}

TEST(stringHelper_Test, SL_StringWithStart)
{

}

TEST(stringHelper_Test, SL_StringIsDirPath)
{

}

TEST(stringHelper_Test, SL_StringIsFilePath)
{

}

TEST(stringHelper_Test, SL_StringDelimDiff)
{

}

TEST(stringHelper_Test, SL_StringDelimSubstring)
{

}

TEST(stringHelper_Test, SL_StringDelimSubstringReverse)
{

}

TEST(stringHelper_Test, SL_StringArrayLog)
{

}

TEST(stringHelper_Test, SL_StringArrayFree)
{

}

TEST(stringHelper_Test, SL_StringArrayPrint)
{

}

TEST(stringHelper_Test, SL_StringFormatPrint)
{

}

