/*
 * THE FILE IS GENERATED by TGen.
 * Thu May 07 07:25:50 2020
 */

#include "unity_fixture.h"
#include "UnityTestFuncName.h"

TEST_GROUP(UnityTestFuncName_Test);

TEST_SETUP(UnityTestFuncName_Test)
{

}

TEST_TEAR_DOWN(UnityTestFuncName_Test)
{

}

TEST(UnityTestFuncName_Test, GetTestFuncDeclare)
{

}

TEST(UnityTestFuncName_Test, GetGroupAndTestName)
{

}

