/*
 * THE FILE IS GENERATED by TGen.
 * Tue May 05 23:03:08 2020
 */

#include "unity_fixture.h"
#include "UnitTestGenerator.h"

TEST_GROUP(UnitTestGenerator_Test);

TEST_SETUP(UnitTestGenerator_Test)
{

}

TEST_TEAR_DOWN(UnitTestGenerator_Test)
{

}

TEST(UnitTestGenerator_Test, readFile)
{

}

TEST(UnitTestGenerator_Test, UnitTestGenerator)
{

}

TEST(UnitTestGenerator_Test, GetFuncsDeclare)
{

}

