/*
 * THE FILE IS GENERATED by TGen, DO NOT EDITE IT.
 * Tue May 05 23:03:09 2020
 */

#include "unity_fixture.h"

TEST_GROUP_RUNNER(CCodeParse_Test)
{
	RUN_TEST_CASE(CCodeParse_Test, CCP_GetCwd);
	RUN_TEST_CASE(CCodeParse_Test, CCP_SetCwd);
	RUN_TEST_CASE(CCodeParse_Test, CCP_IsFilePathVaild);
	RUN_TEST_CASE(CCodeParse_Test, CCP_PrintfMessage);
	RUN_TEST_CASE(CCodeParse_Test, CCP_StringSubtract);
	RUN_TEST_CASE(CCodeParse_Test, CCP_CombinePath);
	RUN_TEST_CASE(CCodeParse_Test, CCP_GetDirFileInfo);
	RUN_TEST_CASE(CCodeParse_Test, CCP_GetFuncNameFormSource);
	RUN_TEST_CASE(CCodeParse_Test, CCP_Free);
}

TEST_GROUP_RUNNER(GeneratorOutputPrivate_Test)
{
	RUN_TEST_CASE(GeneratorOutputPrivate_Test, outputCFileCreate);
	RUN_TEST_CASE(GeneratorOutputPrivate_Test, outputCFileDestory);
	RUN_TEST_CASE(GeneratorOutputPrivate_Test, outputCFileGenerateMessage);
	RUN_TEST_CASE(GeneratorOutputPrivate_Test, outputCFileHead);
	RUN_TEST_CASE(GeneratorOutputPrivate_Test, outputCFileFunctionStart);
	RUN_TEST_CASE(GeneratorOutputPrivate_Test, outputCFileFunctionCall);
	RUN_TEST_CASE(GeneratorOutputPrivate_Test, outputCFileFunctionEnd);
	RUN_TEST_CASE(GeneratorOutputPrivate_Test, outputCFileBlankLine);
}

TEST_GROUP_RUNNER(mpc_Test)
{
	RUN_TEST_CASE(mpc_Test, mpc_err_delete);
	RUN_TEST_CASE(mpc_Test, mpc_err_string);
	RUN_TEST_CASE(mpc_Test, mpc_err_print);
	RUN_TEST_CASE(mpc_Test, mpc_err_print_to);
	RUN_TEST_CASE(mpc_Test, mpc_parse);
	RUN_TEST_CASE(mpc_Test, mpc_nparse);
	RUN_TEST_CASE(mpc_Test, mpc_parse_file);
	RUN_TEST_CASE(mpc_Test, mpc_parse_pipe);
	RUN_TEST_CASE(mpc_Test, mpc_parse_contents);
	RUN_TEST_CASE(mpc_Test, mpc_new);
	RUN_TEST_CASE(mpc_Test, mpc_copy);
	RUN_TEST_CASE(mpc_Test, mpc_define);
	RUN_TEST_CASE(mpc_Test, mpc_undefine);
	RUN_TEST_CASE(mpc_Test, mpc_delete);
	RUN_TEST_CASE(mpc_Test, mpc_cleanup);
	RUN_TEST_CASE(mpc_Test, mpc_any);
	RUN_TEST_CASE(mpc_Test, mpc_char);
	RUN_TEST_CASE(mpc_Test, mpc_range);
	RUN_TEST_CASE(mpc_Test, mpc_oneof);
	RUN_TEST_CASE(mpc_Test, mpc_noneof);
	RUN_TEST_CASE(mpc_Test, mpc_satisfy);
	RUN_TEST_CASE(mpc_Test, mpc_string);
	RUN_TEST_CASE(mpc_Test, mpc_pass);
	RUN_TEST_CASE(mpc_Test, mpc_fail);
	RUN_TEST_CASE(mpc_Test, mpc_failf);
	RUN_TEST_CASE(mpc_Test, mpc_lift);
	RUN_TEST_CASE(mpc_Test, mpc_lift_val);
	RUN_TEST_CASE(mpc_Test, mpc_anchor);
	RUN_TEST_CASE(mpc_Test, mpc_state);
	RUN_TEST_CASE(mpc_Test, mpc_expect);
	RUN_TEST_CASE(mpc_Test, mpc_expectf);
	RUN_TEST_CASE(mpc_Test, mpc_apply);
	RUN_TEST_CASE(mpc_Test, mpc_apply_to);
	RUN_TEST_CASE(mpc_Test, mpc_check);
	RUN_TEST_CASE(mpc_Test, mpc_check_with);
	RUN_TEST_CASE(mpc_Test, mpc_checkf);
	RUN_TEST_CASE(mpc_Test, mpc_check_withf);
	RUN_TEST_CASE(mpc_Test, mpc_not);
	RUN_TEST_CASE(mpc_Test, mpc_not_lift);
	RUN_TEST_CASE(mpc_Test, mpc_maybe);
	RUN_TEST_CASE(mpc_Test, mpc_maybe_lift);
	RUN_TEST_CASE(mpc_Test, mpc_many);
	RUN_TEST_CASE(mpc_Test, mpc_many1);
	RUN_TEST_CASE(mpc_Test, mpc_count);
	RUN_TEST_CASE(mpc_Test, mpc_or);
	RUN_TEST_CASE(mpc_Test, mpc_and);
	RUN_TEST_CASE(mpc_Test, mpc_predictive);
	RUN_TEST_CASE(mpc_Test, mpc_eoi);
	RUN_TEST_CASE(mpc_Test, mpc_soi);
	RUN_TEST_CASE(mpc_Test, mpc_boundary);
	RUN_TEST_CASE(mpc_Test, mpc_boundary_newline);
	RUN_TEST_CASE(mpc_Test, mpc_whitespace);
	RUN_TEST_CASE(mpc_Test, mpc_whitespaces);
	RUN_TEST_CASE(mpc_Test, mpc_blank);
	RUN_TEST_CASE(mpc_Test, mpc_newline);
	RUN_TEST_CASE(mpc_Test, mpc_tab);
	RUN_TEST_CASE(mpc_Test, mpc_escape);
	RUN_TEST_CASE(mpc_Test, mpc_digit);
	RUN_TEST_CASE(mpc_Test, mpc_hexdigit);
	RUN_TEST_CASE(mpc_Test, mpc_octdigit);
	RUN_TEST_CASE(mpc_Test, mpc_digits);
	RUN_TEST_CASE(mpc_Test, mpc_hexdigits);
	RUN_TEST_CASE(mpc_Test, mpc_octdigits);
	RUN_TEST_CASE(mpc_Test, mpc_lower);
	RUN_TEST_CASE(mpc_Test, mpc_upper);
	RUN_TEST_CASE(mpc_Test, mpc_alpha);
	RUN_TEST_CASE(mpc_Test, mpc_underscore);
	RUN_TEST_CASE(mpc_Test, mpc_alphanum);
	RUN_TEST_CASE(mpc_Test, mpc_int);
	RUN_TEST_CASE(mpc_Test, mpc_hex);
	RUN_TEST_CASE(mpc_Test, mpc_oct);
	RUN_TEST_CASE(mpc_Test, mpc_number);
	RUN_TEST_CASE(mpc_Test, mpc_real);
	RUN_TEST_CASE(mpc_Test, mpc_float);
	RUN_TEST_CASE(mpc_Test, mpc_char_lit);
	RUN_TEST_CASE(mpc_Test, mpc_string_lit);
	RUN_TEST_CASE(mpc_Test, mpc_regex_lit);
	RUN_TEST_CASE(mpc_Test, mpc_ident);
	RUN_TEST_CASE(mpc_Test, mpc_startwith);
	RUN_TEST_CASE(mpc_Test, mpc_endwith);
	RUN_TEST_CASE(mpc_Test, mpc_whole);
	RUN_TEST_CASE(mpc_Test, mpc_stripl);
	RUN_TEST_CASE(mpc_Test, mpc_stripr);
	RUN_TEST_CASE(mpc_Test, mpc_strip);
	RUN_TEST_CASE(mpc_Test, mpc_tok);
	RUN_TEST_CASE(mpc_Test, mpc_sym);
	RUN_TEST_CASE(mpc_Test, mpc_total);
	RUN_TEST_CASE(mpc_Test, mpc_between);
	RUN_TEST_CASE(mpc_Test, mpc_parens);
	RUN_TEST_CASE(mpc_Test, mpc_braces);
	RUN_TEST_CASE(mpc_Test, mpc_brackets);
	RUN_TEST_CASE(mpc_Test, mpc_squares);
	RUN_TEST_CASE(mpc_Test, mpc_tok_between);
	RUN_TEST_CASE(mpc_Test, mpc_tok_parens);
	RUN_TEST_CASE(mpc_Test, mpc_tok_braces);
	RUN_TEST_CASE(mpc_Test, mpc_tok_brackets);
	RUN_TEST_CASE(mpc_Test, mpc_tok_squares);
	RUN_TEST_CASE(mpc_Test, mpcf_dtor_null);
	RUN_TEST_CASE(mpc_Test, mpcf_ctor_null);
	RUN_TEST_CASE(mpc_Test, mpcf_ctor_str);
	RUN_TEST_CASE(mpc_Test, mpcf_free);
	RUN_TEST_CASE(mpc_Test, mpcf_int);
	RUN_TEST_CASE(mpc_Test, mpcf_hex);
	RUN_TEST_CASE(mpc_Test, mpcf_oct);
	RUN_TEST_CASE(mpc_Test, mpcf_float);
	RUN_TEST_CASE(mpc_Test, mpcf_strtriml);
	RUN_TEST_CASE(mpc_Test, mpcf_strtrimr);
	RUN_TEST_CASE(mpc_Test, mpcf_strtrim);
	RUN_TEST_CASE(mpc_Test, mpcf_escape);
	RUN_TEST_CASE(mpc_Test, mpcf_escape_regex);
	RUN_TEST_CASE(mpc_Test, mpcf_escape_string_raw);
	RUN_TEST_CASE(mpc_Test, mpcf_escape_char_raw);
	RUN_TEST_CASE(mpc_Test, mpcf_unescape);
	RUN_TEST_CASE(mpc_Test, mpcf_unescape_regex);
	RUN_TEST_CASE(mpc_Test, mpcf_unescape_string_raw);
	RUN_TEST_CASE(mpc_Test, mpcf_unescape_char_raw);
	RUN_TEST_CASE(mpc_Test, mpcf_null);
	RUN_TEST_CASE(mpc_Test, mpcf_fst);
	RUN_TEST_CASE(mpc_Test, mpcf_snd);
	RUN_TEST_CASE(mpc_Test, mpcf_trd);
	RUN_TEST_CASE(mpc_Test, mpcf_fst_free);
	RUN_TEST_CASE(mpc_Test, mpcf_snd_free);
	RUN_TEST_CASE(mpc_Test, mpcf_trd_free);
	RUN_TEST_CASE(mpc_Test, mpcf_all_free);
	RUN_TEST_CASE(mpc_Test, mpcf_strfold);
	RUN_TEST_CASE(mpc_Test, mpcf_maths);
	RUN_TEST_CASE(mpc_Test, mpc_re);
	RUN_TEST_CASE(mpc_Test, mpc_re_mode);
	RUN_TEST_CASE(mpc_Test, mpc_ast_new);
	RUN_TEST_CASE(mpc_Test, mpc_ast_build);
	RUN_TEST_CASE(mpc_Test, mpc_ast_add_root);
	RUN_TEST_CASE(mpc_Test, mpc_ast_add_child);
	RUN_TEST_CASE(mpc_Test, mpc_ast_add_tag);
	RUN_TEST_CASE(mpc_Test, mpc_ast_add_root_tag);
	RUN_TEST_CASE(mpc_Test, mpc_ast_tag);
	RUN_TEST_CASE(mpc_Test, mpc_ast_state);
	RUN_TEST_CASE(mpc_Test, mpc_ast_delete);
	RUN_TEST_CASE(mpc_Test, mpc_ast_print);
	RUN_TEST_CASE(mpc_Test, mpc_ast_print_to);
	RUN_TEST_CASE(mpc_Test, mpc_ast_get_index);
	RUN_TEST_CASE(mpc_Test, mpc_ast_get_index_lb);
	RUN_TEST_CASE(mpc_Test, mpc_ast_get_child);
	RUN_TEST_CASE(mpc_Test, mpc_ast_get_child_lb);
	RUN_TEST_CASE(mpc_Test, mpc_ast_traverse_start);
	RUN_TEST_CASE(mpc_Test, mpc_ast_traverse_next);
	RUN_TEST_CASE(mpc_Test, mpc_ast_traverse_free);
	RUN_TEST_CASE(mpc_Test, mpc_ast_eq);
	RUN_TEST_CASE(mpc_Test, mpcf_fold_ast);
	RUN_TEST_CASE(mpc_Test, mpcf_str_ast);
	RUN_TEST_CASE(mpc_Test, mpcf_state_ast);
	RUN_TEST_CASE(mpc_Test, mpca_tag);
	RUN_TEST_CASE(mpc_Test, mpca_add_tag);
	RUN_TEST_CASE(mpc_Test, mpca_root);
	RUN_TEST_CASE(mpc_Test, mpca_state);
	RUN_TEST_CASE(mpc_Test, mpca_total);
	RUN_TEST_CASE(mpc_Test, mpca_not);
	RUN_TEST_CASE(mpc_Test, mpca_maybe);
	RUN_TEST_CASE(mpc_Test, mpca_many);
	RUN_TEST_CASE(mpc_Test, mpca_many1);
	RUN_TEST_CASE(mpc_Test, mpca_count);
	RUN_TEST_CASE(mpc_Test, mpca_or);
	RUN_TEST_CASE(mpc_Test, mpca_and);
	RUN_TEST_CASE(mpc_Test, mpca_grammar);
	RUN_TEST_CASE(mpc_Test, mpca_lang);
	RUN_TEST_CASE(mpc_Test, mpca_lang_file);
	RUN_TEST_CASE(mpc_Test, mpca_lang_pipe);
	RUN_TEST_CASE(mpc_Test, mpca_lang_contents);
	RUN_TEST_CASE(mpc_Test, mpc_print);
	RUN_TEST_CASE(mpc_Test, mpc_optimise);
	RUN_TEST_CASE(mpc_Test, mpc_stats);
	RUN_TEST_CASE(mpc_Test, mpc_test_pass);
	RUN_TEST_CASE(mpc_Test, mpc_test_fail);
}

TEST_GROUP_RUNNER(stringHelper_Test)
{
	RUN_TEST_CASE(stringHelper_Test, SL_StringTrim);
	RUN_TEST_CASE(stringHelper_Test, SL_StringTrimString);
	RUN_TEST_CASE(stringHelper_Test, SL_StringTrimLeadWhitespace);
	RUN_TEST_CASE(stringHelper_Test, SL_StringReplace);
	RUN_TEST_CASE(stringHelper_Test, SL_StringAppend);
	RUN_TEST_CASE(stringHelper_Test, SL_StringAddHead);
	RUN_TEST_CASE(stringHelper_Test, SL_StringSubstring);
	RUN_TEST_CASE(stringHelper_Test, SL_StringWithEnds);
	RUN_TEST_CASE(stringHelper_Test, SL_StringWithStart);
	RUN_TEST_CASE(stringHelper_Test, SL_StringIsDirPath);
	RUN_TEST_CASE(stringHelper_Test, SL_StringIsFilePath);
	RUN_TEST_CASE(stringHelper_Test, SL_StringDelimDiff);
	RUN_TEST_CASE(stringHelper_Test, SL_StringDelimSubstring);
	RUN_TEST_CASE(stringHelper_Test, SL_StringDelimSubstringReverse);
	RUN_TEST_CASE(stringHelper_Test, SL_StringArrayLog);
	RUN_TEST_CASE(stringHelper_Test, SL_StringArrayFree);
}

TEST_GROUP_RUNNER(UnitTestGenerator_Test)
{
	RUN_TEST_CASE(UnitTestGenerator_Test, readFile);
	RUN_TEST_CASE(UnitTestGenerator_Test, UnitTestGenerator);
	RUN_TEST_CASE(UnitTestGenerator_Test, GetFuncsDeclare);
}

TEST_GROUP_RUNNER(UnitTestRunnerGenerator_Test)
{
	RUN_TEST_CASE(UnitTestRunnerGenerator_Test, PrintGroupMessage);
	RUN_TEST_CASE(UnitTestRunnerGenerator_Test, RunnerGenerator_GetTestGroupAndTestname);
	RUN_TEST_CASE(UnitTestRunnerGenerator_Test, RunnerGenerator_TestGroupAndTestnameDestory);
	RUN_TEST_CASE(UnitTestRunnerGenerator_Test, RunnerGenerator_GeneratorRunnerFile);
	RUN_TEST_CASE(UnitTestRunnerGenerator_Test, RunnerGenerator_GeneratorMainFile);
}

TEST_GROUP_RUNNER(UnityTestFuncName_Test)
{
	RUN_TEST_CASE(UnityTestFuncName_Test, GetTestFuncDeclare);
	RUN_TEST_CASE(UnityTestFuncName_Test, GetGroupAndTestName);
}

