/*
 * THE FILE IS GENERATED by TGen.
 * Tue May 05 23:03:08 2020
 */

#include "unity_fixture.h"
#include "UnitTestRunnerGenerator.h"

TEST_GROUP(UnitTestRunnerGenerator_Test);

TEST_SETUP(UnitTestRunnerGenerator_Test)
{

}

TEST_TEAR_DOWN(UnitTestRunnerGenerator_Test)
{

}

TEST(UnitTestRunnerGenerator_Test, PrintGroupMessage)
{

}

TEST(UnitTestRunnerGenerator_Test, RunnerGenerator_GetTestGroupAndTestname)
{

}

TEST(UnitTestRunnerGenerator_Test, RunnerGenerator_TestGroupAndTestnameDestory)
{

}

TEST(UnitTestRunnerGenerator_Test, RunnerGenerator_GeneratorRunnerFile)
{

}

TEST(UnitTestRunnerGenerator_Test, RunnerGenerator_GeneratorMainFile)
{

}

