/*
 * THE FILE IS GENERATED by TGen.
 * Thu May 07 07:25:50 2020
 */

#include "unity_fixture.h"
#include "utils.h"

TEST_GROUP(utils_Test);

TEST_SETUP(utils_Test)
{

}

TEST_TEAR_DOWN(utils_Test)
{

}

TEST(utils_Test, GetDirentInfo)
{

}

