/*
 * THE FILE IS GENERATED by TGen, DO NOT EDITE IT.
 * Sun Apr 19 17:44:14 2020
 */

#include "unity_fixture.h"

TEST_GROUP_RUNNER(Control)
{
	RUN_TEST_CASE(Control, Ramp);
	RUN_TEST_CASE(Control, Pointer);
}

TEST_GROUP_RUNNER(DIDO)
{
	RUN_TEST_CASE(DIDO, Output);
}

TEST_GROUP_RUNNER(Startup)
{
	RUN_TEST_CASE(Startup, EnableSys);
}

